import type { AIMode } from './gemini';

const GEMINI_API_BASE = 'https://generativelanguage.googleapis.com/v1beta';
const GEMINI_MODEL = 'gemini-3-flash-preview';

const WORKER_BASE = 'https://api.neobrowser.app';
const WORKER_API_KEY = 'd73dfdc0125262f3e1e6fd5f59be8cde31968056e579937283f3e3dc46b67de4';

const SEARCH_PROMPT = `You are a search engine. Given a search query, return realistic, helpful search results as a complete HTML page.

Return ONLY valid JSON:
{
  "title": "Search query - Neo Search",
  "html": "<!DOCTYPE html>...(complete HTML page with search results)..."
}

The HTML page must follow this design EXACTLY:

1. HEADER: Clean white bar with:
   - "neo." logo on left in bold dark text, with a small blue dot after "neo"
   - Search input field showing the current query, styled with rounded corners and a light gray background
   - The search bar should be functional (form that reloads with new query)

2. RESULTS: Show 8-10 realistic, helpful results:
   - Each result has: small green/gray URL breadcrumb on top, blue clickable title (font-size: 20px, no underline, bold on hover), 2-3 line gray description
   - Links should use target="_blank" so they open in new windows
   - Space results well with padding between them (16px between results)
   - No borders between results, clean and spacious like Google

3. SIDEBAR (for certain queries): If the query is about a known entity (person, place, company, etc), show a knowledge card on the right with key facts

4. STYLING:
   - Background: #fff, max-width: 750px for results, font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif
   - Result title color: #1a0dab, visited: #681da8
   - URL color: #006621, font-size: 13px
   - Description: #4d5156, font-size: 14px, line-height: 1.58
   - Fully responsive - works on mobile and desktop
   - Use inline CSS only, no external resources at all
   - Smooth, minimal design inspired by modern search engines

5. FOOTER: Subtle gray text "Results generated by Neo AI" centered at bottom

Make results realistic - use real website names (Wikipedia, Reddit, Stack Overflow, Medium, official sites), realistic URLs, and genuinely helpful descriptions. Results should look like what a real search engine would return.`;

export async function searchWithAI(
  apiKey: string,
  query: string,
  mode: AIMode = 'byok'
): Promise<{ html: string; title: string }> {
  const contents = [
    {
      role: 'user',
      parts: [{ text: `Search query: "${query}"` }],
    },
  ];
  const generationConfig = {
    temperature: 0.7,
    maxOutputTokens: 8192,
    responseMimeType: 'application/json',
  };

  let response: Response;

  if (mode === 'pro') {
    response = await fetch(`${WORKER_BASE}/v1/chat`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'x-api-key': WORKER_API_KEY,
      },
      body: JSON.stringify({
        model: GEMINI_MODEL,
        system_instruction: { parts: [{ text: SEARCH_PROMPT }] },
        contents,
        generationConfig,
      }),
    });
  } else {
    response = await fetch(
      `${GEMINI_API_BASE}/models/${GEMINI_MODEL}:generateContent?key=${apiKey}`,
      {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          system_instruction: {
            parts: [{ text: SEARCH_PROMPT }],
          },
          contents,
          generationConfig,
        }),
      }
    );
  }

  if (!response.ok) {
    throw new Error(`Search failed (${response.status})`);
  }

  const data = await response.json();
  const rawText = data.candidates?.[0]?.content?.parts?.[0]?.text || '';

  try {
    const parsed = JSON.parse(rawText);
    return {
      html: parsed.html || '',
      title: parsed.title || `${query} - Neo Search`,
    };
  } catch {
    throw new Error('Failed to generate search results');
  }
}
